Create Portuguese locale
qbcore-framework/qb-builderjob pull request #11
Opened 2022-01-14 00:22 UTC by DanielCoelh0

2022-01-14 23:53 UTC, Demo4889 approved these changes
approved

2022-01-17 12:06 UTC, pedroalmeida91 requested changes
complete_task = '[~g~E~s~] Terminar Tarega'
 Alterar "Tarefa" por "Tarefa"

2022-01-17 17:13 UTC, DanielCoelh0 commented
> complete_task = '[~g~E~s~] Terminar Tarega' Alterar "Tarega" por "Tarefa"

Obrigado pelo aviso!! O erro já foi corrigido

2022-01-17 17:19 UTC, Demo4889 approved these changes
Approved. Thank you for the corrections. Please use English next time when commenting.

2022-01-17 17:42 UTC, merged